
[git]
tag-pattern = '^v?[0-9]+\.[0-9]+\.[0-9]+$'

[format]
strip-pattern = '^([a-zA-Z]+)(\(.+\))?:\s*'

[[sections]]
title = 'Added'
match = '^(feat|feature)(\(|:)'

[[sections]]
title = 'Fixed'
match = '^fix(\(|:)'

[[sections]]
title = 'Changed'
match = '^(refactor|perf|chore|docs|ci|test)(\(|:)'

[[sections]]
title = 'Other Changes'
match = '.*'
